//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDM.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int Id { get; set; }
        public string ControllerName { get; set; }
        public string Message { get; set; }
        public string Request { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
